version: '3.7'

networks:
  lms-network:
    driver: bridge

services:
# nginx container
  nginx:
    image: nginx:alpine
    container_name: lms-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - lms-network
    volumes:
      - dashboard:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - dashboard

  # admin dashboard
  dashboard:
    image: enegix/lms-dashboard:beta
    container_name: lms-dashboard
    restart: unless-stopped
    expose:
      - '9000'
    networks:
      - lms-network
    environment:
      TZ: Asia/Kuwait
    volumes:
      - dashboard:/var/www
      - uploads:/app/storage/public
    depends_on:
      - mysql
      - redis

# mysql container
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: unless-stopped
    expose:
      - '3306'
    networks:
      - lms-network
    environment:
      MYSQL_DATABASE: lms_024
      MYSQL_ROOT_PASSWORD: lms@root23!pass
      MYSQL_PASSWORD: lms_pass#24
      MYSQL_USER: lms_usr
      SERVICE_NAME: mysql
      TZ: Asia/Kuwait
    volumes:
      - mysql_data:/var/lib/mysql

# phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: lms-phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: lms@root23!pass
      TZ: Asia/Kuwait
      UPLOAD_LIMIT: 300M
    networks:
      - lms-network
    depends_on:
      - mysql

# redis container
  redis:
    image: redis:alpine
    container_name: lms-redis
    restart: unless-stopped
    environment:
      TZ: Asia/Kuwait
    networks:
      - lms-network
    ports:
      - '6379:6379'

# volumes
volumes:
  dashboard:
  mysql_data:
  uploads: